name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Typescript install
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: Typescript build
      run: npm run build 
      working-directory: ./DotnetTemplate.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./DotnetTemplate.Web

  docker_login_and_push:
    name: Docker login, build and push to dokcerhub
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        push: true
        tags: matjadach/module8:${{github.ref_name}}
        no-cache: true


# adding some comment